refactor: use async iterators
libp2p/interface-connection pull request #29
Opened 2019-04-22 14:26 UTC by vasco-santos

BREAKING CHANGE: all the callbacks in the provided API were removed and each function uses aync/await

Needs:

- [ ] suite of tests

2019-04-22 14:28 UTC, vasco-santos commented
@jacobheun @alanshaw @dirkmc can I have your opinion on this proposal? Meanwhile, I will be working on adding a suite of tests and a draft PR for one of the repos using this Interface

2019-04-23 02:47 UTC, dirkmc reviewed
Thanks for putting this together @vasco-santos 

I just made a couple of small suggestions.

2019-04-23 02:47 UTC, dirkmc commented on README.md
> +A valid connection (one that follows this abstraction) connection, must implement the following API:
```suggestion
A valid connection (one that follows this abstraction), must implement the following API:
```

2019-04-23 02:47 UTC, dirkmc commented on README.md
> +Creates a new Connection instance. `connection` is the object responsible for allowing to read or write data through the connection, while `wrappedConnection` consists on another connection that may
I'm not sure it's clear to someone unfamiliar with the API what it means that a connection can be wrapped into another connection

2019-04-23 02:47 UTC, dirkmc commented on README.md
> +  - `Promise<Multiaddr[]> conn.getObservedAddrs()`
Is it necessary for getObservedAddrs() to return a Promise?

2019-04-23 02:47 UTC, dirkmc commented on README.md
> +This method retrieves the a Peer Info object, which contains information about the peer that this conn connects to.
```suggestion
This method retrieves the Peer Info object, which contains information about the peer that this conn connects to.
```

2019-04-23 02:47 UTC, dirkmc commented on src/connection.js
> +      return await this.wrappedConnection.getPeerInfo()
```suggestion
      return this.wrappedConnection.getPeerInfo()
```

2019-04-23 02:47 UTC, dirkmc commented on src/connection.js
> +  async getPeerInfo () {
```suggestion
  getPeerInfo () {
```

2019-04-23 02:47 UTC, dirkmc commented on src/connection.js
> +  async getObservedAddrs () {
```suggestion
  getObservedAddrs () {
```

2019-04-23 02:47 UTC, dirkmc commented on src/connection.js
> +      return await this.wrappedConnection.getObservedAddrs()
```suggestion
      return this.wrappedConnection.getObservedAddrs()
```

2019-04-23 02:47 UTC, dirkmc commented on src/connection.js
> +    await this.connection.close()
Should we close these in parallel? (as they may both time out)

2019-04-23 10:14 UTC, vasco-santos commented on src/connection.js
> +    await this.connection.close()
Initially, I thought about doing these in parallel. However, as we have a connection wrapping the other connection, I thought that we may have problems closing them in parallel, as the wrapping connection may close first. I am not sure if this can be a problem though

2019-04-23 10:24 UTC, vasco-santos commented on README.md
> +  - `Promise<Multiaddr[]> conn.getObservedAddrs()`
I went through all the usages of this interface so far, and I agree with you that we can just return the array of Multiaddr, as I do not see any use case for async interactions. I will modify this

2019-04-23 10:34 UTC, alanshaw requested changes

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +    return ConnectionsPair
What is `ConnectionsPair`? Is this an async function?

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +    // clean up any resources created by setup()
...and return a promise?

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +  - `Promise<> conn.close()`
\+ `conn.source`
\+ `conn.sink`

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +  - `new Connection(connection [, wrappedConnection])`
I'm interested to know if `wrappedConnection` is used and if so what for.

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +  - `Promise<Multiaddr[]> conn.getObservedAddrs()`
It would be nice to have this sync if possible.

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +  - `Promise<Multiaddr[]> conn.getObservedAddrs()`
What are observed addrs? Shouldn't any given connection operate over a single address?

In `go-libp2p` the [connection object](https://godoc.org/github.com/libp2p/go-libp2p-net#Conn) has a property that has a local and remote addr. That makes more sense to me...

2019-04-23 10:34 UTC, alanshaw commented on README.md
>    - `conn.setPeerInfo(peerInfo)`
Are these used? Feels like this information doesn't belong this low down.

2019-04-23 10:34 UTC, alanshaw commented on package.json
>      "pull-defer": "~0.2.3"
Can be removed?

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +It should return a `Promise<peerInfo>`, where peerInfo is a object of type [Peer Info](https://github.com/libp2p/js-peer-info)
```suggestion
It should return a `Promise<PeerInfo>`, which resolves to a [PeerInfo](https://github.com/libp2p/js-peer-info) object
```

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +It should return a `Promise<multiaddrs>`, where `multiaddrs` is an array of [multiaddr](https://github.com/multiformats/multiaddr).
```suggestion
It should return a `Promise<Multiaddr[]>`, which resolves to an array of [Multiaddr](https://github.com/multiformats/multiaddr).
```

2019-04-23 10:34 UTC, alanshaw commented on README.md
> +  - `new Connection(connection [, wrappedConnection])`
We should probably not call the first parameter `connection` - it makes it seem like you must pass an instance of `Connection`.

You should actually pass a [streaming iterables duplex object](https://gist.github.com/alanshaw/591dc7dd54e4f99338a347ef568d6ee9#duplex-it).

It's probably also worth mentioning that `Connection` is compatible with the streaming iterables duplex object interface.

2019-04-23 10:38 UTC, vasco-santos commented on README.md
> +Creates a new Connection instance. `connection` is the object responsible for allowing to read or write data through the connection, while `wrappedConnection` consists on another connection that may
I have been discussing this with @jacobheun 

We should not need the wrapped connection anymore because we don't have to support deferred connections, as a result of not being necessary to return a connection before it is actually ready with this async endeavour. Also, this `wrappedConnection` adds confusion and overhead to the connection logic.

The problem here is the usage of this wrappedConnection logic in some modules and removing it now will introduce a lot of other changes unrelated to the async migration. 

We can remove this if we are all comfortable with making this change. Otherwise, we can tackle it in a next step. Let me know your ideas

2019-04-23 11:01 UTC, vasco-santos commented on README.md
> +  - `new Connection(connection [, wrappedConnection])`
When I did this, I had some thought on the name of this parameter. I started by calling it `stream` and I ended up moving because I thought it could get confused with the `Stream` interface too. However, I totally agree that `connection` is also a bad name. 

Can you think of any good naming here? Otherwise, we have to get a strange and long combination of `streaming iterables duplex object`

2019-04-23 11:02 UTC, vasco-santos commented on README.md
> +  - `new Connection(connection [, wrappedConnection])`
Can you look at https://github.com/libp2p/interface-connection/pull/29/files#r277615681 for more context?

2019-04-23 11:05 UTC, vasco-santos commented on README.md
>    - `conn.setPeerInfo(peerInfo)`
`setPeerInfo` is used in the context of the "wrappedConnection" and ensures that the peerInfo is set recursively on all Connection instances. It is typically called after crypto has identified and verified the peer. If we decide to get rid of the wrappedConnection, we can also remove this

2019-04-23 11:29 UTC, vasco-santos commented on README.md
> +  - `Promise<Multiaddr[]> conn.getObservedAddrs()`
I agree with you, a connection operates over a single address!

I also agree with `go-libp2p` connection object. I will remove this function in favor of `getConnectionMultiaddrs()`

2019-04-23 12:09 UTC, jacobheun commented on README.md
> +Creates a new Connection instance. `connection` is the object responsible for allowing to read or write data through the connection, while `wrappedConnection` consists on another connection that may
Yeah, wrapped is a misnomer. Ultimately it's a reference to an origin Connection to keep the PeerInfo and ObserverAddrs records up to date for all associated Connections. The existing connection pipeline constantly has `new Connection()` being used to "transform" the connection at various steps when including things like multistream, secio, or stream muxing.

This is where I think a basic test suite here would be really useful in determining what's needed and how we should be handling connection "upgrading", as well as providing working examples of how to use Connections.

2019-05-10 11:52 UTC, vasco-santos commented
I have been thinking about the interface's current implementation and there are several things that do not make sense to me. Moreover, as we have an ongoing effort for the libp2p introspection, there is a lot of data missing in `js-libp2p` to make it possible.

According to the `libp2p` docs, a connection consists of a "bundle" of streams. However, in this `interface-connection` a connection is a raw connection, from where we can read and write data (it is a stream). All this naming made me really confused and after checking the interface for [go-libp2p-net](https://github.com/libp2p/go-libp2p-net/blob/master/interface.go#L94), I realized that we should leverage this refactor to improve the current logic, as well as to enable the libp2p introspection.

In the interface connection from the go implementation, it is provided a way to open streams and it stores the streams associated with the connection. Afterward, there is also an interface for streams, which is in reality what we were trying to achieve here.

I have discussed this with @jacobheun and we agreed that being able to implement an echo protocol as follows, would be a big improvement:

```js
// An echo protocol
const echo = (stream) => { /* Runs the protocol over this stream */ }

// A new connection and echo
const connection = await libp2p.connect(peerInfo)
const stream = connection.newStream()
await echo(stream)

// An existing connection
const connection = await libp2p.getConnection(peerInfo)
const stream = connection.newStream()
await echo(stream)
``` 

In this context, I created a draft for the [`interface-connection`](https://gist.github.com/vasco-santos/bc89fe6e0acf8186f1137576135fbd49) and [`interface-stream`](https://gist.github.com/vasco-santos/a3edcf2bbb17e6ca62fff07be256e17b) that I would like feedback.

2019-05-22 17:25 UTC, vasco-santos commented
@jacobheun @alanshaw @dirkmc 

Updated this PR with my new proposal. I will work on a PR on top of [libp2p/js-libp2p-tcp#102](https://github.com/libp2p/js-libp2p-tcp/pull/102) to integrate this and see how it goes. Meanwhile, I would like some feedback

2019-05-22 18:55 UTC, dirkmc reviewed
This looks like a big step in the right direction, thanks for putting this together @vasco-santos 🎉

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +`isInitiator` is a `boolean` for signaling if the peer creating the connection instance was the responsible for the creation of the connection. Default value: `true`.
```suggestion
`isInitiator` is a `boolean` indicating whether the peer creating the Connection instance initiated the connection. Default value: `true`.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +
It may be useful to people unfamiliar with the Connection interface to change the name of `peerInfo` to `remotePeerInfo`

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +`encryption` is a `string` with the encryption protocol.
May be useful to give an example of an `encryption` string

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +`protocol` is the intended protocol to use. This is optional and may be `undefined`.
May be useful to have an example of a `protocol` string

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +It returns a `Promise` with the intance of the created `Stream`.
```suggestion
It returns a `Promise` with the instance of the created `Stream`.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This method closes a connection with other peer, as well as all the streams running in the connection.
```suggestion
This method closes the connection to the remote peer, as well as all the streams running in the connection.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This property contains the status of the connection. It can be either `OPEN`, `CLOSED` or `CLOSING`.
It may be useful to explain under which circumstances the state changes

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This property contains an object with the `local` and `remote` multiaddrs as properties. While the connection was not upgraded and `identify` finished, the `local` multiaddr is `undefined`.
```suggestion
This property contains an object with the `local` and `remote` multiaddrs as properties. The `local` multiaddr is `undefined` until the connection is upgraded and `identify` finishes.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This property contains an object with the `open` and `close` timestamps of the connection. While the connection was not closed, the `close` timestamp is `undefined`.
```suggestion
This property contains an object with the `open` and `close` timestamps of the connection. The `close` timestamp is `undefined` until the connection is closed.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This property contains the reference for the `multiplexer` being used in the connection. Before the connection being upgraded, this is `undefined`.
```suggestion
This property contains a reference to the `multiplexer` being used in the connection. It is `undefined` until the connection has been upgraded.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This property contains the encryption method being used in the connection. Before the connection being upgraded, this is `undefined`.
```suggestion
This property contains the encryption method being used in the connection. It is `undefined` until the connection has been upgraded.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This property contains an array of tags associated with the connection. New tags can be pushed to this array during the connection life.
```suggestion
This property contains an array of tags associated with the connection. New tags can be pushed to this array during the connection's lifetime.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +`isInitiator` is a `boolean` for signaling if the peer creating the stream instance was the responsible for the creation it. Default value: `true`.
```suggestion
`isInitiator` is a `boolean` indicating whether the peer creating the Stream instance initiated the stream. Default value: `true`.

```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This getter returns the reference to the connection "source", which is an iterable object that can be consumed.
```suggestion
This getter returns a reference to the connection "source", which is an iterable object that can be consumed.
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This getter returns the reference to the connection "sink", which is an iterator that consumes (or drains) a source.
```suggestion
This getter returns a reference to the connection "sink", which is an iterator that consumes (or drains) a source. 
```

2019-05-22 18:55 UTC, dirkmc commented on README.md
> +This property contains an object with the `open` and `close` timestamps of the stream. While the stream was not closed, the `close` timestamp is `undefined`.
```suggestion
This property contains an object with the `open` and `close` timestamps of the stream. The `close` timestamp is `undefined` until the stream is closed.
```

2019-05-22 18:55 UTC, dirkmc commented on src/connection.js
> +    if (this.status === STATUS.CLOSING) {
Is it necessary to throw an error if the connection is closing / closed? It might make cleanup code in the clients of this class simpler if it simply returns once the connection has closed, or immediately if it has already closed

2019-05-22 18:55 UTC, dirkmc commented on src/stream.js
> +   * Sink it function. This function takes a source and iterates over it.
It may be clearer to call this function `drain`. To "drain the sink" means to let all the water run out of the sink.

2019-05-22 18:55 UTC, dirkmc commented on src/stream.js
> +    if (this.timeline.close) {
It may simplify clients to just return immediately if the stream is already closed

2019-05-23 10:36 UTC, vasco-santos commented on src/connection.js
> +    if (this.status === STATUS.CLOSING) {
My reasoning was to guarantee to the user that is intention really happens. But in this, I am willing to go with your suggestion as this can lead to an error closing, while it is being closed at the same time.

2019-05-23 10:36 UTC, vasco-santos commented on src/connection.js
> +    if (this.status === STATUS.CLOSING) {
Please check my new logic on this and elt me know what you think

2019-05-23 10:36 UTC, vasco-santos commented on src/stream.js
> +   * Sink it function. This function takes a source and iterates over it.
I like `drain` better as well 👍 

@alanshaw called it `sink` in https://gist.github.com/alanshaw/591dc7dd54e4f99338a347ef568d6ee9. I would like to wait for his feedback then, as he may have a good reason for the naming.

2019-05-23 13:18 UTC, dirkmc commented on src/connection.js
> +
I was thinking that if `close()` has already been called, any subsequent call to `close()` will return a Promise that resolves when it has eventually closed. Something like:
```
  if (this._closing) {
    return this._closing
  }
  this._closing = closeStreams()
  await this._closing
  this.status = STATUS.CLOSED
```

2019-05-23 13:18 UTC, dirkmc commented on README.md
> +This property contains the status of the connection. It can be either `OPEN`, `CLOSED` or `CLOSING`. Once the creating is created it is in an `OPEN` status. When a `conn.close()` happens, the status
```suggestion
This property contains the status of the connection. It can be either `OPEN`, `CLOSED` or `CLOSING`. Once the connection is created it is in an `OPEN` status. When a `conn.close()` happens, the status will change to `CLOSING` and finally, after all the connection streams are properly closed, the status will be `CLOSED`.
```

2019-05-23 13:22 UTC, dirkmc commented on README.md
> +`options.signal` is a boolean for using the abortable signal. Default value: `true`.
I'm not sure it's clear what it means if `options.signal` is set to `true`. People viewing the docs may not know what abortable signals are, maybe we could add a sentence here with a brief explanation

2019-05-23 13:22 UTC, dirkmc commented on src/connection.js
> +  /**
Could you explain what this code is used for? Is this to do with how the switch works?

2019-05-28 14:07 UTC, vasco-santos commented on src/connection.js
> +  /**
I am still not sure if we need this, as well as how it will look like. 

Basically, we need a way in the peer that is receiving the `newStream` "request" to add the stream in its array of streams.

2019-05-28 14:08 UTC, vasco-santos commented on README.md
> +`options.signal` is a boolean for using the abortable signal. Default value: `true`.
I will add it

2019-05-28 14:25 UTC, vasco-santos commented
cc @jacobheun @dirkmc @vmx 

The problem that I described during the JS Core Sync call was basically the distinction between a socket in the "connection" created and the `connection` of the `interface-connection`.

For example, in [libp2p/js-libp2p-tcp#102](https://github.com/libp2p/js-libp2p-tcp/pull/102) we have the following codebase:

```js
class TCP {
  async dial (ma, options) {
    const cOpts = ma.toOptions()
    const rawSocket = await this._connect(cOpts, options)
    return new Libp2pSocket(rawSocket, ma, options)
  }
}
```

The `rawSocket` is a node stream, which consists of the underlying raw duplex connection between two nodes. It is not a stream within the connection, according to what we consider a stream.

My main concern was regarding the representation of this `socket` within our connection but luckily @jacobheun provided me a really nice approach to this.

Stating what I just added to the Readme:

## Connection

Before creating a connection from a transport compatible with `libp2p` it is important to understand some concepts:

- **socket**: the underlying raw duplex connection between two nodes. It is created by the transports during a dial/listen.
- **connection**: the abstract libp2p duplex connection between two nodes. The transport must pipe the `socket` through the connection.
- **stream**: a single duplex channel of the `connection`. Each connection may have many streams.

A connection stands for the libp2p communication duplex layer between two nodes. It is **not** the underlying raw transport duplex layer (socket), such as a TCP socket, but an abstracted duplex layer that sits on top of the raw socket.

When a libp2p transport creates its socket, a new `connection` instance should be created and the transport should **pipe** both input and output of the socket through this `connection`, i.e. `pipe(socket, connection, socket)`.

The transport must handle the translation of cleanup from the socket to the connection. That is, the errors, resets or closes on the socket **must** be passed to the connection. In the same way, the transport **must** map these actions from the `connection` to the socket. This helps ensuring that the transport is responsible for socket management, while also allowing the application layer to handle the connection management.

```js
const pipe = require('it-pipe')
const { Connection } = require('interface-connection')

class Transport {
  async dial () {
    // ...

    // create the raw socket and the connection
    const socket = await this._connect()
    const conn = new Connection(remotePeerInfo, remoteMa)

    // pipe the socket through the connection (if necessary include a conversion to iterable duplex streams)
    pipe(socket, conn, socket)

    // bind the necessary handlers to update state changes (error, close, reset, ...)
    // ...

    return conn
  }

  _connect () {}
}
```

Let me know what you guys think

2019-05-28 16:09 UTC, dirkmc commented on src/connection.js
> +  /**
Sorry I was referring to the code below, in `_hasMultiplexerOrErrored()` :)

2019-05-28 16:14 UTC, dirkmc commented
Very nice explanation, I like it a lot 👍

2019-05-30 14:26 UTC, dirkmc commented on src/connection.js
> +    this._closing = await this._closeStreams()
```suggestion
    this._closing = this._closeStreams()
    await this._closing
```

2019-07-08 14:21 UTC, achingbrain commented on README.md
> +`options.signal` is a boolean for using the abortable signal. Default value: `true`.
Maybe it could be `options.abortable`?

2019-07-08 16:12 UTC, achingbrain commented on src/stream.js
> +   * Sink it function. This function takes a source and iterates over it.
I think it's just because it's what [`pull-stream`](https://www.npmjs.com/package/pull-stream) calls it.  No need to be constrained by that.

2019-07-15 13:53 UTC, vasco-santos commented on README.md
> +`options.signal` is a boolean for using the abortable signal. Default value: `true`.
I also like abortable more! Will change it

2019-07-15 14:04 UTC, vasco-santos commented on src/connection.js
> +  /**
Ok, so when the connection is established, we are not able to open a stream immediately. We need to wait for it to be multiplexed before. This aims to try to wait before failing.

2019-07-22 15:31 UTC, vasco-santos commented
@jacobheun @dirkmc 

I made a few changes on the approach. Basically, if we want to go with the pipe approach, we need to have the `sink` and `source` functions in the `interface-connection` class, which by design does not look good to me. The `interface-transport` expects an iterable connection.

I changed the approach for the transports to extend the connection using their raw socket as follows:

```js
const abortable = require('abortable-iterator')

const { Connection } = require('interface-connection')

class Libp2pSocket extends Connection {
  constructor (rawSocket, ma, opts = {}) {
    super(ma, opts)

    this._rawSocket = rawSocket

    this.sink = this._sink(opts)
    this.source = opts.signal ? abortable(rawSocket.source, opts.signal) : rawSocket.source
  }

  _sink (opts) {
    return async (source) => {
      try {
        await this._rawSocket.sink(abortable(source, opts.signal))
      } catch (err) {
        // Re-throw non-aborted errors
        if (err.type !== 'aborted') throw err
        // Otherwise, this is fine...
        await this._rawSocket.close()
      }
    }
  }
}

module.exports = Libp2pSocket
```

```js
const Libp2pSocket = require('./socket')

class Transport {
  async dial () {
    // ...

    // create the raw socket and the connection
    const socket = await this._connect()
    const conn = new libp2pSocket(socket, remoteMa, {})

    return conn
  }

  _connect () {}
}
```

I got inspiration on the `libp2p-tcp` PR for async await, as it was creating this Libp2pSocket wrapper. With this approach in mind, I created 2 PRs, one for `libp2p-tcp` and one for `libp2p-websockets` with this version of the interface:

https://github.com/libp2p/js-libp2p-tcp/pull/109
https://github.com/libp2p/js-libp2p-websockets/pull/88

There are some tests failing. The majority is related to the adapter tests for `interface-transport`, which expect the older `interface-connection` API.

I think that this approach is cleaner and more appropriate to the transport implementation. This approach also helps ensuring that the transport is responsible for socket management, while also allowing the application layer to handle the connection management.

Let me know your thoughts

2019-07-23 14:23 UTC, dirkmc commented
This does seem like a better approach to me 👍

2019-07-23 14:31 UTC, jacobheun commented
I think the thing we just need to do for this to get to a final decisions is to actually exchange data over a muxed connection with this, the async tcp transport, and the mplex iterator. It will force us to make sure the mplex async version is done and we'll catch usability issues for this. i think it's going to be hard to nail down a version until that's done. That or we may make big changes to this after the fact.

2019-07-24 19:21 UTC, vasco-santos commented
I agree! I will work on that experiment and let you know!

2019-08-06 16:24 UTC, achingbrain commented on package.json
> +    "mocha": "^6.1.4",
Should mocha be a devDependency instead?

2019-08-06 16:43 UTC, vasco-santos commented on package.json
> +    "mocha": "^6.1.4",
good catch!

2019-08-06 17:10 UTC, vasco-santos commented
@jacobheun @dirkmc @achingbrain 

I did some experiments with this implementation, `js-libp2p-tcp` and `it-mplex`:

```js
{
  "name": "test-interface-connection",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "interface-connection": "libp2p/interface-connection#refactor/async",
    "it-mplex": "alanshaw/it-mplex#master",
    "it-pipe": "^1.0.1",
    "libp2p-tcp": "libp2p/js-libp2p-tcp#chore/add-interface-connection",
    "multiaddr": "^6.1.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

```js
'use strict'

const multiaddr = require('multiaddr')
const TCP = require('libp2p-tcp')

const Mplex = require('it-mplex')
const pipe = require('it-pipe')

const main = async () => {
  const ma = multiaddr('/ip4/127.0.0.1/tcp/9090')
  const tcp = new TCP()

  // Create a listener with the handler
  const listener = tcp.createListener((conn) => {

    // create a duplex muxer
    const muxer = new Mplex({
      onStream: async stream => {
        // Read from this stream and write back to it (echo server)
        pipe(
          stream,
          source => (async function* () {
            for await (const data of source) yield data
          })(),
          stream
        )
      }
    })

    pipe(conn, muxer, conn) // conn is duplex connection to another peer
  })

  // Listen on the multi-address
  await listener.listen(ma)

  // Dial to that same address
  const conn = await tcp.dial(ma)

  // create a duplex muxer for connection
  const muxer = new Mplex({
    onStream: stream => {
      conn.onNewStream(stream)
    }
  })

  // Upgrade connection
  // await _switch.connectionUpgrader.privatize(connection)
  // const encryption = await _switch.connectionUpgrader.encrypt(connection)  // `encryption` is negotiated
  // const multiplexer = await _switch.connectionUpgrader.multiplex(connection) // `multiplexer` is negotiated
  pipe(conn, muxer, conn) // conn is duplex connection to another peer

  conn.upgraded(muxer, '/secio/1.0.0')
  
  // run identify
  // nextTick(() => _switch.identifyService.identify(connection)) // runs identify (this probably shouldn't block the return) and sets `localAddress`
  //conn.setLocalAddress(ma)

  const stream = await conn.newStream() // Create a new duplex stream to the remote

  // Use the duplex stream to send some data to the remote...
  pipe([1, 2, 3], stream._iterableDuplex) // TODO: DISCUSSION?

  // Close the listener
  await listener.close()
  await stream.close()
}

main()

```

Regarding the discussion that I inserted a `TODO: DISCUSSION?`, after checking the implementation for `it-mplex`, I noticed that I am doing some work that it is already handled by the `it-mplex` (https://github.com/alanshaw/it-mplex/blob/master/src/stream.js). So, as this will also be different on `spdy` for instance, I think we should just add a getter in the Stream instance for the iterableDuplex, and we could remove all the logic inherent to it, keeping the metadata logic and the relationship from the connection with the stream. 

Other than that, I think that we can go forward with this. Let me know your thoughts

2019-08-07 11:17 UTC, achingbrain commented on src/stream.js
> +    this.id = (~~(Math.random() * 1e9)).toString(36) + Date.now()
Can you just use `parseInt` or `Math.floor` instead of `~~` here?  This is not a hot codepath so micro optimisations like this just make the code harder to read.

2019-08-07 11:18 UTC, achingbrain commented on package.json
> +    "err-code": "^1.1.2",
v2 of `err-code` is out that removes `throw errcode('aargh', 'ERR_CODE')` in favour of `throw errcode(new Error('aargh'), 'ERR_CODE')` for less misleading stack traces..

2019-08-07 11:32 UTC, achingbrain commented
```javascript
const stream = await conn.newStream()

pipe([1, 2, 3], stream._iterableDuplex) // TODO: DISCUSSION?
```

Could we not return the actual iterable from `conn.newStream()`?

Then we could do:

```javascript
const stream = await conn.newStream()

pipe([1, 2, 3], stream)
```

I guess we'd have to augment it with the `close` function, etc and maybe a `.meta` object with the `id`, `timeline`, properties etc.

2019-08-07 11:54 UTC, jacobheun commented
Is there anything preventing us from just making `Stream` an iterable duplex? We should do whatever we need to do to wrap the underlying iterable duplex so we can interact with the `Stream` instance directly.

2019-08-07 17:30 UTC, achingbrain commented
"Iterable duplex" is something we've invented, right? Shouldn't it just be an async generator?

2019-08-07 21:16 UTC, vasco-santos commented on package.json
> +    "err-code": "^1.1.2",
Actually noticed the new version today in other repo! Will update it

2019-08-07 21:22 UTC, vasco-santos commented on src/stream.js
> +    this.id = (~~(Math.random() * 1e9)).toString(36) + Date.now()
I guess you have a point! Agree with improving readability

2019-08-07 21:31 UTC, vasco-santos commented
> Is there anything preventing us from just making `Stream` an iterable duplex? We should do whatever we need to do to wrap the underlying iterable duplex so we can interact with the `Stream` instance directly.

I agree and that was my initial go. However, when we create a new stream with it-mplex, it creates the iterable duplex as follows:

https://github.com/alanshaw/it-mplex/blob/master/src/stream.js#L34-L76

It has some logic inherent to multiplex, so we can't just move all this logic to the `Stream`. What would be the best way to wrap this via the class?

> "Iterable duplex" is something we've invented, right? Shouldn't it just be an async generator function?

Yes, I think @alanshaw may have some points to add here

2019-08-08 08:39 UTC, alanshaw commented
Please see my response here https://gist.github.com/alanshaw/591dc7dd54e4f99338a347ef568d6ee9#gistcomment-2993182

2019-08-27 13:40 UTC, vasco-santos commented
We can now do:

```js
const stream = await conn.newStream() // Create a new duplex stream to the remote

// Use the duplex stream to send some data to the remote...
pipe([1, 2, 3], stream)
```

I wrapped the underlying iterable duplex as jacob suggested

2019-08-27 14:26 UTC, alanshaw commented
I'm slowly getting to this. I'm currently fixing up `libp2p-tcp` and what is returned from it...here's some notes I made over the weekend:

> A "libp2p Connection" is something the transport layer should not know about.
> 
> A "libp2p Connection" would usefully have `PeerInfo`, and a way to get a new muxed stream.
> 
> I think at the transport layer we're dealing with "sockets"? - yes, well no, go calls them "multiaddr-net connections" https://github.com/multiformats/go-multiaddr-net
> 
> "multiaddr-net connections" - have a `LocalMultiaddr` and `RemoteMultiaddr` property and a reference to golang's underlying `Conn`.
> 
> In Go, a `Stream` is what is returned by the muxer and you can call `Conn()` to get hold of the `libp2p connection`. I think we should do something similar.
> 
> https://godoc.org/github.com/libp2p/go-libp2p-core/network#Stream
> 
> go tcp transport is passed a "transport upgrader" that upgrades sockets to muxed and secure Connections.
> 
> https://github.com/libp2p/go-tcp-transport/blob/master/tcp.go#L69
> https://github.com/libp2p/go-libp2p-transport-upgrader
> 
> "close" makes sense for js multiaddr-net-conns and echos https://golang.org/pkg/net/#Conn

---

Right now I'm most interested in what we're returning from transports. There's 3 types of objects at play here:

## `multiaddr-net Connection`

This is what transports create, it has no knowledge of the peer but knows about that the local and remote addresses it is connected to are. It is a _duplex iterable stream_ (i.e. has a `sink` and a `source` property) that has additional properties for getting the local and remote addresses (I propose this is `.localAddr` and `.remoteAddr`) and for closing the connection (I propose this is `.close`).

I'm currently altering `js-libp2p-tcp` and `js-libp2p-websockets` to return this object.

## `libp2p Connection`

Is something that knows about the peer it's connected to and has multiplexing built in. It should also be a _duplex iterable stream_ with additional properties for getting a new multiplexed stream (I propose this is `.newStream`), the remote peer info (I propose this is `remotePeer`) _and_ the underlying `multiaddr-net Connection` (I propose this is just `.conn`). See https://godoc.org/github.com/libp2p/go-libp2p-core/network#Conn and it's mixins for the inspiration here (as well as other properties we may want to consider).

In `go-libp2p` this is the object that is returned by libp2p transports, but it obtained by passing a `multiaddr-net Connection` to an `Upgrader` which is dependency injected into the transport.

In `js-libp2p` we don't have an "`Upgrader`" and we somehow return `Connection` objects from transports...We don't have to have one, but if we don't, we should really be returning `multiaddr-net Connection` objects from transports not `libp2p Connection` objects and let the switch do the upgrade (as it does now).

## `Stream`

A muxed stream, this is the object you get if you call `newStream` on a `libp2p Connection` object. It is a _duplex iterable stream_ with an additional property to get hold of the underlying `libp2p Connection` (I propose this is just `.conn`) as well as a `.close` and `.reset` property (this is consistent with what `it-mplex` is returns https://github.com/alanshaw/it-mplex#const-stream--muxernewstreamoptions).

---

I hope this makes sense and moves some of this knowledge out of my head - sorry for not communicating this sooner but I've basically been trying to figure this out myself and realised that what I had come up with was _strikingly_ similar to what `go-libp2p` had implemented already, so that is super re-assuring.

2019-08-27 16:04 UTC, jacobheun commented
@alanshaw it makes sense and the proposals look good, but the transport dial return type may complicate things. 

The major complication I see with the transports returning a `multiaddr-net Connection` instead of a `libp2p Connection` is with the Circuit transport. It deals with libp2p connections because it is using upgraded connections from other transports, so returning a `multiaddr-net Connection` doesn't make sense. There may be other instances where a transport needs a `libp2p Connection` before executing its dialing logic (signaling nodes for distributed signaling for example).

The advantage of being consistent with returning `libp2p Connection` is that it provides more flexibility in the future to connections that need to do more complex interactions.

We could mimic go more closely and pass the upgrader via libp2p to the transports on creation so that transports are returning fully upgraded connections.

I need to think through this a bit more, but those are my initial thoughts.

2019-08-27 17:32 UTC, vasco-santos commented
Thanks for your brain dump Alan!

My thoughts about the `libp2p connection` are mostly aligned with yours. Just a small difference regarding the internal `conn`. However, this is also related to the discussion of what should the transport return. I was until now thinking about returning the libp2p connection, but in a way where the transport extended the libp2p connection to add its own things. That is, the `libp2p-tcp` would return an instance that extends that `libp2p-interface` class and adds it the `_conn` / `rawSocket`, and potentially other things it needs.

I feel you also have a good point on: 

> A "libp2p Connection" is something the transport layer should not know about.

I was totally on the favor of returning the libp2p connection from the transport, but you made me think that we should probably not allow the transport to hurt the connection somehow. We need to find a good solution for the `libp2p-circuit` though.
 
Other than Jacob's points, I also wanted to remove a lot of the complexity inside `libp2p-switch`, which will be more difficult if we do not return the `libp2p-connection` from the transport.

2019-08-28 12:09 UTC, alanshaw commented
> We could mimic go more closely and pass the upgrader via libp2p to the transports on creation so that transports are returning fully upgraded connections.

If circuit needs to operate on `libp2p Connection` objects then it sounds like it makes sense to pass an upgrader as go-libp2p does. Existing transports can use the upgrader to obtain a `libp2p Connection` to _return_ and the circuit can use it to obtain one that it can operate on...

Caveat: I've not looked at the circuit code closely yet so I'm not certain if this is will be ok - perhaps you can confirm?

As @vasco-santos mentioned a separate "upgrader" would move some complexity out of the switch (or at least force it to be more modular within libp2p core).

2019-08-28 12:38 UTC, jacobheun commented
@alanshaw yes that will work. My thought is that js-libp2p will instantiate transports with a reference to it, `new Transport({ ...options, libp2p })`.  _Note_: It currently passes libp2p in the options to avoid backwards compatibility issues, but we could separate those out as part of the refactor.

Most transports would need the upgrader, so they could get this from libp2p, `return await libp2p.upgrade(multiaddrNetConn)`. Other transports like Circuit and potentially a signaling transport, would use `libp2p.dial(...)` to create a connection over other transports. Regardless of the transport, the end result would be a returned libp2p connection.

2019-08-28 12:54 UTC, vasco-santos commented
> @alanshaw yes that will work. My thought is that js-libp2p will instantiate transports with a reference to it, `new Transport({ ...options, libp2p })`. _Note_: It currently passes libp2p in the options to avoid backwards compatibility issues, but we could separate those out as part of the refactor.
> 
> Most transports would need the upgrader, so they could get this from libp2p, `return await libp2p.upgrade(multiaddrNetConn)`. Other transports like Circuit and potentially a signaling transport, would use `libp2p.dial(...)` to create a connection over other transports. Regardless of the transport, the end result would be a returned libp2p connection.

This sounds a good approach to me!

2019-08-28 13:02 UTC, alanshaw commented
> @alanshaw yes that will work. My thought is that js-libp2p will instantiate transports with a reference to it, `new Transport({ ...options, libp2p })`. _Note_: It currently passes libp2p in the options to avoid backwards compatibility issues, but we could separate those out as part of the refactor.

I'm a big fan of just passing the things a module needs so it's explicit about what it depends on. It just makes it way easier to understand and reason about without having to delve into the code to find out what part of the giant state blob it's using. So I'd be -1 on passing the whole of `libp2p` to it, but it's up to you guys :)

> Most transports would need the upgrader, so they could get this from libp2p, `return await libp2p.upgrade(multiaddrNetConn)`.

...they could, but personally I'd just give them an "upgrader" instance that they can use.

> Other transports like Circuit and potentially a signaling transport, would use `libp2p.dial(...)` to create a connection over other transports.

[Circuit is not a transport 😉](https://github.com/libp2p/js-libp2p-circuit#implementation-rational) and a special case. If we need to pass `libp2p` here then so be it. [`go-libp2p-circuit` has access to the host (libp2p)](https://github.com/libp2p/go-libp2p-circuit/blob/master/relay.go#L43).

> Regardless of the transport, the end result would be a returned libp2p connection.

👍

2019-08-28 13:41 UTC, jacobheun commented
Passing libp2p is really to get around the lack of dependency injection. Several libp2p modules need some information/methods from libp2p, but there's no clean way to access that.

> Circuit is not a transport 😉 and a special case.

I would argue the correctness of that. I know it's in the implementation notes, but it is a transport imo, it just happens to **also** leverage other transports. Go also wraps Relay in the Transport interface, they just have the advantage of being able to inject the Host.

> I'm a big fan of just passing the things a module needs so it's explicit about what it depends on

I agree, however, this makes things difficult when creating new modules or transports for libp2p that need to do more complex things that require more information from the Host. This was an issue with some of the star servers for a while that needed access to their own identity, but they couldn't cleanly get that without creating the transport before adding it to libp2p.

> but personally I'd just give them an "upgrader" instance that they can use

I am fine with passing an upgrader to the transport, but I think we should pass the libp2p instance as well to get around the current DI limitation. The advantage of passing these separately would be that most of the core transports could just ignore the libp2p option altogether.

2019-09-06 08:10 UTC, jacobheun commented
Just to close the loop here, Transports will now be passed an `Upgrader` instance when they are created by Libp2p, https://github.com/libp2p/interface-transport/pull/53. The upgrader will be responsible for taking a `transport-multiaddr-connection{ sink, source, conn, remoteAddr }`, and upgrading it into an `interface-connection`. That result will be returned by the Transport on dial and for incoming connections.

This will also make it much easier for the Switch to continue dialing other known addresses for a peer, if the initial connection is successful but upgrading fails (such as SECIO).

2019-09-06 15:59 UTC, alanshaw requested changes

2019-09-06 15:59 UTC, alanshaw commented on README.md
> +When a libp2p transport creates is socket, a new instance should be created by extending the `connection` from `interface-connection` and transforming it into an iterable.
I'm not sure I understand this sentence?

2019-09-06 15:59 UTC, alanshaw commented on README.md
> +module.exports = Libp2pSocket
What is this example illustrating? Is it necessary?

The transport should create a `multiaddr connection` and pass it to an upgrader to turn it into an `interface-connection` connection.

2019-09-06 15:59 UTC, alanshaw commented on README.md
> +- **socket**: the underlying raw duplex connection between two nodes. It is created by the transports during a dial/listen.
```suggestion
- **socket**: the underlying raw duplex connection between two nodes. It is created by the transports during a dial/listen.
- **multiaddr connection**: an abstraction over the socket to allow it to work with multiaddr addresses. It is a duplex connection that transports create to wrap the socket before passing to an upgrader that turns it into a standard connection (see below).
```

An upgrader should accept a multiaddr connection `{ sink, source, conn, remoteAddr, localAddr? }` and return a `interface-connection` connection.

* `conn` is the `socket`
* `remoteAddr` is a Multiaddr for the remote (MAY include Peer ID)
* `localAddr` is an (optional) Multiaddr for the local address this connection is bound to

2019-09-06 15:59 UTC, alanshaw commented on README.md
> +- **connection**: the abstract libp2p duplex connection between two nodes. The transport must pipe the `socket` through the connection.
```suggestion
- **connection**: a connection between two _peers_ that has built in multiplexing and info about the connected peer. It is created from a [multiaddr connection](https://github.com/libp2p/interface-transport#multiaddrconnection) by an upgrader. The upgrader uses multistream-select to add secio and multiplexing and returns this object.
```

2019-09-06 15:59 UTC, alanshaw commented on README.md
> +- **stream**: a single duplex channel of the `connection`. Each connection may have many streams.
```suggestion
- **stream**: a muxed duplex channel of the `connection`. Each connection may have many streams.
```

2019-09-06 15:59 UTC, alanshaw commented on README.md
> +  - `Promise<> conn.close()`
I propose:

```
  - `const conn = new Connection({ localAddr, remoteAddr, localPeer, remotePeer, newStream, close, direction })`
  - `conn.localAddr: Multiaddr` // Get/set local Multiaddr (set from maConn.localAddr initially)
  - `conn.remoteAddr: Multiaddr` // Get remote Multiaddr (proxy to maConn.remoteAddr)
  - `conn.localPeer: PeerId` // Peer ID of the local peer
  - `conn.remotePeer: PeerId` // Peer ID of the remote peer
  - `conn.newStream(protocol): Promise<Stream>` // Function that gets a new muxed+multistream-selected stream
  - `conn.getStreams(): Stream[]`
  - `conn.close(): Promise`
  - `conn.direction: String` ("inbound" or "outbound")
```

...you can add some other stuff but this is probs the minimum.

Inspired by https://godoc.org/github.com/libp2p/go-libp2p-core/network#Conn

So the upgrader might look something like this:

```js
const { Connection } = require('interface-connection')
const MSS = require('multistream-select')
const pipe = require('it-pipe')
const log = require('debug')(`libp2p:upgrader`)

class Upgrader {
  constructor ({
    peerId, // this node's peer id
    streamMuxer, // stream muxer class as passed to libp2p config
    onStream, // called when the muxer receives a request for a new stream
    protocols // protocols this node can speak/handle
  }) {
    this._peerId = peerId
    this._Muxer = streamMuxer
    this._onStream = onStream
    this._protocols = protocols
  }

  async upgradeOutbound (maConn) {
    const muxer = new this._Muxer({
      onStream: async muxedStream => {
        const mss = new MSS.Listener(muxedStream)
        const { stream, protocol } = await mss.handle(this._protocols)
        this._onStream({ stream: { conn, ...stream }, protocol })
      }
    })

    const newStream = async protocols => {
      const muxedStream = muxer.newStream()
      const mss = new MSS.Dialer(muxedStream)
      const { stream, protocol } = await mss.select(protocols)
      return { stream: { conn, ...stream }, protocol }
    }

    let remotePeer
    /*
      ...secio to obtain remotePeer ID ...
      // Like:?
      const secioStream = await newStream('/secio/1.0.0')
      remotePeerId = await pipe([], secioStream, () => {})
    )
    */

    const conn = new Connection({
      localAddr: maConn.localAddr,
      remoteAddr: maConn.remoteAddr,
      localPeer: this._peerId,
      remotePeer,
      newStream,
      close: err => maConn.close(err),
      direction: 'outbound'
    })

    pipe(maConn, muxer, maConn)
      .catch(err => log('connection error %s (%s)', maConn.remoteAddr, remotePeer, err))

    return conn
  }

  // ...similar for upgradeInbound
}

module.exports = Upgrader
```

2019-09-08 09:45 UTC, vasco-santos commented on README.md
> +When a libp2p transport creates is socket, a new instance should be created by extending the `connection` from `interface-connection` and transforming it into an iterable.
this is not relevant now, as a result of the way transports use the upgrader with our current idea. I will remove it

2019-09-08 09:45 UTC, vasco-santos commented on README.md
> +module.exports = Libp2pSocket
I will remove it. Not relevant anymore with the upgrader logic

2019-09-08 20:28 UTC, vasco-santos commented on README.md
> +  - `Promise<> conn.close()`
LGTM! I will change according to this

2019-09-12 15:58 UTC, jacobheun commented on README.md
> +  - `Promise<> conn.close()`
Overall I think this looks good. I am currently working through some issues getting the connection fully upgraded with plaintext 2.0.0 and the muxer.

In regards to the constructor, it was updated to assert the existence of things. The main drawback I see here is that we lose timeline information. We have to select/perform crypto before we select a muxer. Only then can we create the Connection instance, which means `timeline.open` is some time after this, and not when the transport handed off the base MultiaddrConnection.

I propose to remove the assert logic altogether and let the Upgrader be responsible for doing the right thing, it allows for more flexibility, and gives us the full timeline from transport handoff till close. I think it would be better to have setters for the remaining metadata, or a static method for attaching it to the Connection instance. ie:

```js
class Upgrader {
  ...
  async upgradeOutbound (maConn) {
    const connection = new Connection({ 
      remoteAddr: maConn.remoteAddr,
      localPeer: this._peerId,
      direction: DIRECTION.OUTBOUND 
    })

    // [Privatize], Encrypt, Mux

    return Connection.attach(connection, {
      remotePeer,
      newStream,
      close: err => maConn.close(err),
      ...
    })
  }
}
```

2019-09-12 16:56 UTC, vasco-santos commented on README.md
> +  - `Promise<> conn.close()`
Yeah, you are right regarding the timeline. Also, the connection state will be affected.

I like your example suggestion!

2019-09-13 14:08 UTC, alanshaw commented on README.md
> +This property contains an object with the `open` and `close` timestamps of the stream. The `close` timestamp is `undefined` until the stream is closed.
Please clarify format and precision

2019-09-13 14:08 UTC, alanshaw commented on README.md
> +  - `Promise<> conn.close()`
The open timestamp isn't necessarily going to be correct this way. It'll be the time that upgrader was called but anything could have happened between the socket being opened and the upgrader being called.

```js
const maConn = await socket.open()
const openTime = Date.now() // opened now
await pause(500) // for example, but could be anything...
const conn = await upgrader.upgradeOutbound(maConn)
console.log(conn.timeline.open) // openTime + 500
```

What if the open/close timestamp information was a property on the `maConn` and that it is passed to `Connection` when created?

```js
    const conn = new Connection({
      timeline: {
        open: maConn.timeline.open,
        upgraded: Date.now()
      },
      localAddr: maConn.localAddr,
      remoteAddr: maConn.remoteAddr,
      localPeer: this._peerId,
      remotePeer,
      newStream,
      close: err => maConn.close(err),
      direction: 'outbound'
    })
```

It is the **transport's responsibility** to set this timestamp correctly when it creates the connection. Then we don't need `Connection.attach` and can just create a full connection object in one shot.

2019-09-13 14:51 UTC, alanshaw requested changes

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +- **multiaddr connection**: an abstraction over the socket to allow it to work with multiaddr addresses. It is a duplex connection that transports create to wrap the socket before passing to an upgra
```suggestion
- **[multiaddr connection](https://github.com/libp2p/interface-transport#multiaddrconnection)**: an abstraction over the socket to allow it to work with multiaddr addresses. It is a duplex connection that transports create to wrap the socket before passing to an upgrader that turns it into a standard connection (see below).
```

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +  - `<PeerInfo> conn.remotePeer`
Do we need to duplicate `PeerInfo` from the peer book in every `Connection`? Can it just be the `PeerId` and if you need to know more you look it up in the peer book?

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +  - `<Direction> conn.direction`
```suggestion
  - `<String> conn.direction`
```

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +  - `Promise<Stream> conn.newStream(protocol, options)`
```suggestion
  - `Promise<Stream> conn.newStream(protocol, [options])`
```

Worth noting that protocol can be an array of protocols (in case you speak different versions).

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +This property contains the direction of the peer in the stream. It can be `INBOUND` or `OUTBOUND`.
Please clarify type

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +  - `stream.source()`
```suggestion
  - `stream.source` - iterable object
```

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +  - `stream.drain()`
```suggestion
  - `stream.sink` - Function
```

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +`protocol` is the intended protocol to use. This is optional and may be `undefined`. Example: `/echo/1.0.0`
Not optional! `multistream-select` needs to know what protocol to speak.

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +`options.abortable` is a boolean for using the abortable signal. Default value: `true`.
We've used `signal` in many other places (and also to follow the option name in the `fetch` API) and it should be passed an [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal)

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +This property contains the status of the connection. It can be either `OPEN`, `CLOSED` or `CLOSING`. Once the connection is created it is in an `OPEN` status. When a `conn.close()` happens, the statu
Please clarify type. Also, can be string? "open", "closed", "closing"? Also this is an appropriate place to mention how I get hold of the "OPEN", "CLOSING" or "CLOSED" constants.

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +This property contains an object with the `local` and `remote` multiaddrs as properties. The `local` multiaddr is `undefined` until the connection is upgraded and `identify` finishes.
Remove this? It is just `localAddr` and `remoteAddr` right?

Also, `localAddr` will be populated initially but it may not have the peer ID.

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +This property contains the direction of the peer in the connection. It can be `INBOUND` or `OUTBOUND`.
Please clarify type, also this is an appropriate place to mention how I get hold of the "INBOUND" or "OUTBOUND" constants.

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +This property contains a reference to the `multiplexer` being used in the connection. It is `undefined` until the connection has been upgraded.
A `Connection` is multiplexed and encrypted. This should always have a value.

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +This property contains the encryption method being used in the connection. It is `undefined` until the connection has been upgraded.
Encryption is optional right?

```suggestion
This property contains the encryption method being used in the connection. It is `undefined` if the connection is not encrypted.
```

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +`direction` is a `Direction` indicating whether the connection is `INBOUND` or `OUTBOUND`.
\+ multiplexer + encryption

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +`options.abortable` is a boolean for using the abortable signal. Default value: `true`.
`options.signal` instead?

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +- `JavaScript` - `const stream = new Stream(iterableDuplex, connection, isInitator, options)`
`new Stream({ ... })` - object syntax like in `Connection`

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +This property contains a reference to the `multiplexer` being used in the connection. It is `undefined` until the connection has been upgraded.
Can just be the codec for the multiplexer? Does it need to be the full instance?

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +- `JavaScript` - `conn.direction`
Do you think we should group metadata like direction, multiplexer, encryption into a `stat` property like `go-libp2p` https://godoc.org/github.com/libp2p/go-libp2p-core/network#Conn

```js
con.stat.direction
con.stat.multiplexer
con.stat.encryption
```

2019-09-13 14:51 UTC, alanshaw commented on README.md
> +`connection` is a reference to the connection associated with this stream.
In `Multiaddr Connection` we use `conn` to reference the underlying connection. Maybe we should use the same here or change `Multiaddr Connection`?

2019-09-13 16:35 UTC, jacobheun commented on README.md
> +  - `<PeerInfo> conn.remotePeer`
I kind of want to get rid of PeerInfo altogether. Really, the peerstore should just keep track of peer ids and their associated metadata.

2019-09-13 16:35 UTC, jacobheun commented on README.md
> +  - `Promise<> conn.close()`
This sounds good to me.

2019-09-16 13:58 UTC, vasco-santos commented on README.md
> +This property contains the status of the connection. It can be either `OPEN`, `CLOSED` or `CLOSING`. Once the connection is created it is in an `OPEN` status. When a `conn.close()` happens, the statu
I will use the strings then

2019-09-17 13:04 UTC, jacobheun commented on README.md
> +## Modules that implement the interface
I think we can just delete this section, it doesn't really make sense anymore as the modules don't implement the interface, they use an upgrader to return them. js-libp2p is the thing that will implement this.

2019-09-17 13:04 UTC, jacobheun commented on test/compliance.spec.js
> +describe('compliance tests', () => {
I added this test suite, which will run the actual compliance tests we exported. This made it easy to spot some bugs we've missed over the last few iterations. I also updated the travis file and package.json so these run on CI.

The main idea here, aside from actually testing the code, is to verify the exported tests are also working properly without relying on checking it against another module (like we are currently doing with the muxer and transport interfaces). I think for test setup we could expand this to use a pseudo muxer and pseudo encryption, and enforce implementations to at least create an echo connection (supporting '/echo/1.0.0') so that we can also do some basic validation that data is being exchanged properly.

2019-09-17 13:55 UTC, vasco-santos commented on README.md
> +## Modules that implement the interface
I was thinking that once we get this into `js-libp2p`, that we would run these tests into the transports test suite. This way, we can guarantee that each transport calls the `js-libp2p` upgrader as expected.

2019-09-17 13:59 UTC, jacobheun commented on README.md
> +## Modules that implement the interface
It would make sense to run these on the js-libp2p Upgrader, but I think we can skip the addition to transports. The interface-transport suite already validates that the upgrader is being called, and that what it returns is what the transport returns. https://github.com/libp2p/interface-transport/blob/master/src/dial-test.js#L65

I would expect that anytime someone is creating an Upgrader, such as the Switch dialer, they should run this test suite against the connections created from that.

2019-09-17 14:04 UTC, vasco-santos commented on README.md
> +## Modules that implement the interface
ok, seems a good approach! I will remove this section then

2019-09-17 15:57 UTC, alanshaw requested changes

2019-09-17 15:57 UTC, alanshaw commented on src/connection.js
> +  onNewStream ({ stream, protocol }) {
Where does this get called?

2019-09-17 15:57 UTC, alanshaw commented on src/connection.js
> +    await this._closing
This is unnecessary - closing the connection should close all the streams mplex has created.

2019-09-17 15:57 UTC, alanshaw commented on src/connection.js
> +    }))
How does this list shrink?

2019-09-17 15:57 UTC, alanshaw commented on src/stream.js
> +        await this._iterableDuplex.sink(abortable(source, this._options.signal))
I think that [mplex should take care of making the stream abortable](https://github.com/alanshaw/it-mplex/issues/1) as it should be able to do this in mplex using [`abortable.multi`](https://github.com/libp2p/js-libp2p-mplex/pull/94/files#diff-1a805c2ce2ff5b0b11bd883157fc5473R56-R59) to avoid adding another async boundary around the sink.

To explain, `pipe(source, transform, sink)` is effectively `sink(transform(source()))` and each one of these is an async function that adds an async boundary. The longer this pipeline is the slower the stream becomes because we have to hop over multiple boundaries to pull the chunk through the async functions. Abortable is just a transform that races an AbortSignal and the next chunk so I added `abortable.multi` to allow multiple aborters but only one async boundary.

2019-09-17 21:04 UTC, vasco-santos commented on src/connection.js
> +    }))
I am not sure if I get your question?

2019-09-17 21:05 UTC, vasco-santos commented on src/connection.js
> +  onNewStream ({ stream, protocol }) {
Considering that peerA does `newStream` in a connection with peerB, peerB needs to add the stream data to its connection as well.

2019-09-17 21:06 UTC, vasco-santos commented on src/connection.js
> +    await this._closing
ok, that is nice, just saw that reviewing mplex!

2019-09-17 21:07 UTC, vasco-santos commented on src/connection.js
> +    await this._closing
we need to call this just for updating the close stream timestamp, but we don't need to have this async close on `stream.js`

2019-09-18 09:24 UTC, jacobheun commented on src/connection.js
> +    }))
We need to add a test to ensure we're getting rid of tracked connections, otherwise this will grow indefinitely. Something like:
1. Create 3 streams
1. Ensure we're tracking 3 streams
1. Close each stream
1. Ensure we're tracking 0 streams

2019-09-18 09:49 UTC, vasco-santos commented on src/connection.js
> +    }))
That makes sense, yes! Commit in a sec

2019-09-18 09:57 UTC, jacobheun commented on src/connection.js
> +  onNewStream ({ stream, protocol }) {
This is likely something we will have to test with the Upgrader. I also propose we change this to `addStream` and have it return the created `Stream`. It would enable us to consolidate some logic here.

```js
addStream({ stream, protocol, direction = 'inbound' }): Stream
```

When the dialer creates a new stream it's easy to track because it's called from the Connection. All incoming streams are created at the muxer level. So, when the Upgrader adds the `onStream` method to the muxer, it also needs to send that info to the connection for tracking. `Stream` in `interface-connection` should **just** be a metadata wrapper for the underlying muxed stream. `interface-connection` should only care when the muxed stream is created and when it ends, we're not currently tracking the latter (which we need for pruning the streams list).

In regards to tracking the end of streams, we currently have metadata for tracking the opening and end of a stream. When a stream ends, we should be removing it from tracking, because we don't want that sitting around in memory. For introspection for the visualizer effort, we will need to provide a snapshot (logs?) of the Stream at close before removing it from tracking.

2019-09-18 10:13 UTC, vasco-santos commented on src/connection.js
> +  onNewStream ({ stream, protocol }) {
I will change the naming and the return part.

Regarding direction, why provide a way to put it `outbound`? It seems it will always be `inbound`

> So, when the Upgrader adds the onStream method to the muxer, it also needs to send that info to the connection for tracking.

Yes, that is my thought!

> In regards to tracking the end of streams, we currently have metadata for tracking the opening and end of a stream. When a stream ends, we should be removing it from tracking, because we don't want that sitting around in memory. For introspection for the visualizer effort, we will need to provide a snapshot (logs?) of the Stream at close before removing it from tracking.

Yes, we have metadata enough for the introspection in this case.

2019-09-18 10:23 UTC, vasco-santos commented on src/connection.js
> +  onNewStream ({ stream, protocol }) {
I pushed the renaming + return part

2019-09-18 10:52 UTC, jacobheun commented on src/connection.js
> +  onNewStream ({ stream, protocol }) {
Because then we can use it in `newStream`, and the Upgrader doesn't have to care about setting the direction. If we want to change how we're tracking/creating streams in the future, it can all be done in addStream.

```js
const { stream, protocol } = await this._newStream(protocols)
return this.addStream({
  stream,
  direction: 'outbound',
  protocol
})
```

2019-09-18 11:02 UTC, vasco-santos commented on src/connection.js
> +  onNewStream ({ stream, protocol }) {
Seems good, I just added direction option support as well!

2019-09-18 11:33 UTC, alanshaw commented on src/connection.js
> +    }))
Can getStreams just be a passthrough to the muxer (i.e have it passed to the connection constructor like newstream and close)? Mplex already  tracks both inbound and outbound streams so it would be trivial to add a method to get hold of them.

2019-09-18 11:36 UTC, jacobheun commented on src/connection.js
> +  onNewStream ({ stream, protocol }) {
I noticed `interface-transport` wasn't properly checking timeline stats in tests (and found a bug with the tcp close timeline), so I created a PR for that and the transport close method, https://github.com/libp2p/interface-transport/pull/55.

2019-09-18 11:52 UTC, jacobheun commented on src/connection.js
> +    }))
If we passthrough to the muxer how do we get the metadata? We could separate that from streams, eliminating the need for `Stream` and just use the underlying `MuxedStream`. We'd still need to know when streams are created and closed to manage the metadata, but that might help keep separation of concerns a bit cleaner.

2019-09-18 12:07 UTC, vasco-santos commented on src/connection.js
> +    }))
Having things like tags and metadata in the `MuxedStream` seems strange IMHO.

2019-09-18 12:15 UTC, jacobheun commented on src/connection.js
> +    }))
Yes, I agree, aside for timeline. What I am referring to is something like this for the muxer:
```js
// In Upgrader
const muxer = new Muxer({
  onStream: async muxedStream => {
    log('new stream requested')
    const mss = new MSS.Listener(muxedStream)
    const { stream, protocol } = await mss.handle(this._protocols)
    connection.addStream(stream, protocol)
  },
  onStreamEnd: (id) => {
    log('stream ended')
    connection.removeStream(id)
  }
})
```

And then addStream / removeStream on `Connection` could manage metadata separate from the stream.
```js
// In Connection
this.streamRegistry = new Map()
....
addStream(muxedStream, protocol) {
  // Add a metadata object for the stream
  this.streamRegistry.set(muxedStream.id, {
    tags: [],
    protocol
  })
}
removeStream(id) {
  // Do any final tracking/logging of the metadata and then remove it
  this.streamRegistry.delete(id)
}
```

2019-09-18 12:20 UTC, vasco-santos commented on src/connection.js
> +    }))
I am ok with that, but what will the `getStreams` return?

Passthrough to the muxer and grab data from the `streamRegistry`?

2019-09-18 12:33 UTC, jacobheun commented on src/connection.js
> +    }))
It would be a passthrough, but I wouldn't merge the metadata on return. I think it would be helpful to understand what `getStreams` would be used for. Introspection is the main thing that comes to mind. I see `getStreams` or simple `get streams ()` as being a proxy to the muxers list of streams. We can pass that to the Connection constructor. That would allow me to do any operation on the stream itself, which really shouldn't be needed, or check out its timeline. If I wanted to get additional stats on the stream I could then run `connection. streamRegistry.get(stream.id)` (or just `connection.registry.get(stream.id)`) and get the additional. This also better supports lazy loading the data, which would be helpful for a visualizer UI.

2019-09-18 13:06 UTC, alanshaw commented on src/connection.js
> +    }))
If there’s no concrete use case for this right now we could just punt on it and implement it later when needed. That might help get this merged faster?

2019-09-18 13:10 UTC, vasco-santos commented on src/connection.js
> +    }))
It will be introspection, as you mentioned. The use case will be: "Get every stream from a specific connection". 

We are talking on an RPC protocol with the metadata in the introspection side of things. In this way, the UI will probably not leverage lazy loading on this level, since we will need to provide everything on the data model (or diffs).

We can do this as you suggest, do `get streams ()` and then iterate on each one and get its metadata, or we can have an api function for it.

2019-09-18 13:36 UTC, vasco-santos commented on src/connection.js
> +    }))
I did some changes according to this discussion, need to update the readme if you agree: 
https://github.com/libp2p/interface-connection/pull/29/commits/199be5d2248021f4df316d55c3186ba15b9dd57d

2019-09-18 14:19 UTC, jacobheun reviewed
Some small changes otherwise I think this gets us what we need and should simplify things. I'll work on a PR for interface-stream-muxer to include the `timeline`, `onStreamEnd` and a way to get all streams.

2019-09-18 14:19 UTC, jacobheun commented on src/connection.js
> +    return muxedStream
We should return the protocol here, it got lost moving things around (we should add a test for it). If I do `connection.newStream(['/echo/2.0.0', '/echo1.0.0'])`, I don't want to have to check the registry to see what protocol was decided.
```js
const { stream, protocol } = connection.newStream(['/echo/2.0.0', '/echo1.0.0'])
switch (protocol) {
   ...
}
```

2019-09-18 14:19 UTC, jacobheun commented on src/connection.js
> +  addStream (muxedStream, protocol, tags = []) {
Nothing is settings tags. Let's make `addStream` take an object and drop tags for now. We can do a follow up release with it when we have a better idea of the use, and wont need to deal with param changes if needed. I don't see it getting used this way.

2019-09-18 14:19 UTC, jacobheun commented on src/connection.js
> +  get registry () {
I'd just drop the getter and change `streamRegistry` to `registry` everywhere. The extra getter and variable isn't getting us anything.

2019-09-23 13:43 UTC, jacobheun reviewed
Some minor things after the latest changes. I'm leveraging this in the latest version of the switch dial flow I am working on and everything is looking pretty good. After this round I think this should be good to merge and we can do any additional changes in followup PRs.

2019-09-23 13:43 UTC, jacobheun commented on README.md
> +  - `Promise<object> conn.newStream(Array<protocols>)`
```suggestion
  - `Promise<object> conn.newStream(Array<protocols>)`
  - `<void> conn.removeStream(id)`
```

2019-09-23 13:43 UTC, jacobheun commented on README.md
> +- `JavaScript` - `conn.addStream(stream, protocol, metadata)`
```suggestion
- `JavaScript` - `conn.addStream(stream, { protocol, ...metadata })`
```

2019-09-23 13:43 UTC, jacobheun commented on README.md
> +`metadata` is an object containing the stream metadata (such as its `tags`).
```suggestion
`metadata` is an object containing any additional, optional, stream metadata that you wish to track (such as its `tags`).

#### Remove a from the registry

- `JavaScript` - `conn.removeStream(id)`

Removes the stream with the given id from the connection registry.

`id` is the unique id of the stream for this connection.

```

2019-09-23 13:43 UTC, jacobheun commented on src/connection.js
> +  addStream (muxedStream, protocol, metadata = {}) {
Per the above suggestion I think we should make this `addStream (muxedStream, { protocol, metadata })`

2019-09-26 12:43 UTC, jacobheun approved these changes
This looks good! Let's merge this monster!

2019-09-27 09:13 UTC, merged